version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ironcalc_ironcalc_1
      APP_PORT: 2080

  ironcalc:
    image: ghcr.io/ironcalc/ironcalc-caddy:0.6.0
    volumes:
      - ${APP_DATA_DIR}/data:/data
