version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ironcalc_web_1
      APP_PORT: 2080

  web:
    image: ghcr.io/ironcalc/ironcalc-caddy:0.6.0
    volumes:
      - ${APP_DATA_DIR}/data/app_data:/data
      - ${APP_DATA_DIR}/data/caddy/caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - server

  server:
    image: ghcr.io/ironcalc/ironcalc-server:0.6.0
    volumes:
      - ${APP_DATA_DIR}/data:/data
