version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ironcalc_web_1
      APP_PORT: 2080

  web:
    image: ghcr.io/ironcalc/ironcalc-caddy:0.6.0@sha256:53771742646e388dcaec283b8247b59f1a8677903354b7d7d125d012fee22809
    volumes:
      - ${APP_DATA_DIR}/data:/data