version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-viniplay_app_1
      APP_PORT: 8998

  app:
    image: ardovini/viniplay:latest
    volumes:
      - ${APP_DATA_DIR}/data/app_data:/data
      - ${APP_DATA_DIR}/data/dvr:/dvr
    environment:
      SESSION_SECRET: f3c1f9c4e0914c5ab8d2b6f0e7a1c9d3f4a8b7e2c5d90123ac7f5e9b0d4c6a8f
      VAPID_CONTACT_EMAIL: mailto:your_email@example.com