version: "3.7"

services:
  web:
    image: ghcr.io/teamhypersomnia/hypersomnia-server:latest
    volumes:
      - ${APP_DATA_DIR}/data:/root/.config/Hypersomnia/user
    ports:
      - "3399:8412/udp"
      - "9099:9000/udp"
    restart: on-failure
