version: "3.7"

services:
  web:
    image: ghcr.io/teamhypersomnia/hypersomnia-server:latest
    user: "1000:1000"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data:/home/hypersomniac/.config/Hypersomnia/user
    # FÃ¼r echte Verbindungen aus LAN/Internet brauchst du die UDP-Ports:
    ports:
      - "8412:8412/udp"   # Game
      - "9000:9000/udp"   # Web-UDP-Mux (laut Logs aktiv)
    restart: on-failure
