version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-hypersomnia_web_1
      APP_PORT: 8412

  web:
    image: ghcr.io/teamhypersomnia/hypersomnia-server:latest
    volumes:
      - ${APP_DATA_DIR}/data:/home/hypersomniac/.config/Hypersomnia/user
    restart: on-failure