version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-wastebin_web_1
      APP_PORT: 8088

  web:
    image: quxfoo/wastebin:3.4.0@sha256:30dac17168952582ac5db5ac5581d14cd1421be4a111f0d20e8b2d0e353ee357
    volumes:
      - ${APP_DATA_DIR}/data:/data