version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-netbird_web_1
      APP_PORT: 80

  app:
    image: netbirdio/netbird:latest
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/app_data:/var/lib/netbird

  web:
    image: nginx:1.27@sha256:124b44bfc9ccd1f3cedf4b592d4d1e8bddb78b51ec2ed5056c52d3692baebc19
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/www:/usr/share/nginx/html:ro
