version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-overleaf_web_1
      APP_PORT: 80

  web:
    image: sharelatex/sharelatex:latest
    depends_on:
      - mongo
      - redis
    environment:
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      SHARELATEX_REDIS_HOST: redis
      REDIS_HOST: redis
      SHARELATEX_APP_NAME: "Overleaf Community Edition"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "true"
      TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var
    volumes:
      - ${APP_DATA_DIR}/data/sharelatex:/var/lib/sharelatex

  mongo:
    image: mongo:4.0
    expose:
      - "27017"
    volumes:
      - ${APP_DATA_DIR}/data/mongo:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo localhost:27017/test --quiet"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:5
    expose:
      - "6379"
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
