version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-overleaf_web_1
      APP_PORT: 80

  web:
    image: sharelatex/sharelatex:latest
    depends_on:
      - mongo
      - redis
    environment:
      OVERLEAF_APP_NAME: "Overleaf Community Edition"
      OVERLEAF_SITE_URL: "http://umbrel.local:8063"
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "true"
      TEXMFVAR: /var/lib/overleaf/tmp/texmf-var
    volumes:
      - ${APP_DATA_DIR}/data/sharelatex:/var/lib/overleaf

  mongo:
    image: mongo:6.0
    expose:
      - "27017"
    volumes:
      - ${APP_DATA_DIR}/data/mongo:/data/db

  redis:
    image: redis:5
    expose:
      - "6379"
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
