version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-notediscovery_web_1
      APP_PORT: 8000

  web:
    image: ghcr.io/gamosoft/notediscovery:0.6.1@sha256:2b60def9c2567ec785eb728ed2845291db2bfd83d81c9da4e9d87481a37fcbb7
    volumes:
      - ${APP_DATA_DIR}/data/app_data:/app/data
      - ${APP_DATA_DIR}/data/plugins:/app/plugins
      - ${APP_DATA_DIR}/data/themes:/app/themes
      - ${APP_DATA_DIR}/data/config.yaml:/app/config.yaml
