version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-liquid-photos_app_1
      APP_PORT: 6363

  app:
    image: nikunjsingh/liquid-photos:latest
    restart: on-failure
    environment:
      HOST: "0.0.0.0"
      PORT: "6363"
      ADMIN_USER: "admin"
      ADMIN_PASS: "umbrel"
    volumes:
      - ${APP_DATA_DIR}/data/pictures:/pictures:ro
      - ${APP_DATA_DIR}/data/cache:/app/.cache
