version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ungoogled-chromium_nginx_1
      APP_PORT: 8080

  web:
    image: lscr.io/linuxserver/ungoogled-chromium:latest
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Berlin
      LC_ALL: de_DE.UTF-8
      # Optional nur f√ºrs LAN:
      # CUSTOM_USER: umbrel
      # PASSWORD: umbrel
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
    shm_size: "2gb"

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - web
    volumes:
      - ${APP_DATA_DIR}/data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
