version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ungoogled-chromium_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/linuxserver/ungoogled-chromium:142.0.7444@sha256:5492444fe33866a8717a2e79e66e1820eb7c2c2a67441bf79f8ac77733eff644
    volumes:
      - ${APP_DATA_DIR}/data:/config:rw
    mem_limit: 3g
    shm_size: 1g
    cpu_shares: 1024
    restart: on-failure
    environment:
      PUID: 1000
      PGID: 1000
