version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-wally_web_1
      APP_PORT: 80

  web:
    image: poliuscorp/wally:1.6@sha256:76b8f997a444236d00007e2f2c291567e86beb2c2bce6accfc87760ffb90eebd
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/wally/data
    environment:
      DEMO: "false"