version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-wally_web_1
      APP_PORT: 80

  web:
    image: poliuscorp/wally:1.9@sha256:dfcfbf0f5f7bfd2d33a3c5854101a46daff563c4a1124e1330d70094942997ff
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/wally/data
    environment:
      DEMO: "false"