version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ampache_app_1
      APP_PORT: 80

  app:
    image: ampache/ampache:latest
    volumes:
      - ${APP_DATA_DIR}/data/media:/media:ro
      - ${APP_DATA_DIR}/data/config:/var/www/config
    environment:
      - TZ=Europe/Berlin
