version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-sparkyfitness_web_1
      APP_PORT: 80

  db:
    image: postgres:15-alpine
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_DB: sparky
      POSTGRES_USER: sparkyuser
      POSTGRES_PASSWORD: sparkypass
    volumes:
      - ${APP_DATA_DIR}/sparkyfitness-db:/var/lib/postgresql/data

  server:
    image: codewithcj/sparkyfitness_server:latest
    depends_on:
      - db
    environment:
      SPARKY_FITNESS_LOG_LEVEL: INFO
      SPARKY_FITNESS_APP_DB_USER: sparkyuser
      SPARKY_FITNESS_APP_DB_PASSWORD: sparkypass
      SPARKY_FITNESS_DB_USER: sparkyuser
      SPARKY_FITNESS_DB_PASSWORD: sparkypass
      SPARKY_FITNESS_DB_HOST: db
      SPARKY_FITNESS_DB_NAME: sparky
      SPARKY_FITNESS_DB_PORT: 5432
      SPARKY_FITNESS_SERVER_PORT: 3010
      NODE_ENV: production
      TZ: Europe/Bucharest
      SPARKY_FITNESS_API_ENCRYPTION_KEY: dOxZYTTZgXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpWzqzKaUOIOGGIr
      JWT_SECRET: ${APP_SEED}
      SPARKY_FITNESS_FRONTEND_URL: http://${DEVICE_DOMAIN_NAME}:8944
      SPARKY_FITNESS_DISABLE_SIGNUP: "false"

  web:
    image: codewithcj/sparkyfitness:latest
    depends_on:
      - server
