version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-sparkyfitness_sparkyfitness-web_1
      APP_PORT: 80

  sparkyfitness-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sparky
      POSTGRES_USER: sparkyuser
      POSTGRES_PASSWORD: sparkypass
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/postgresql/data

  sparkyfitness-server:
    image: codewithcj/sparkyfitness_server:latest
    depends_on:
      - sparkyfitness-db
    restart: on-failure
    environment:
      SPARKY_FITNESS_LOG_LEVEL: INFO
      SPARKY_FITNESS_APP_DB_USER: sparkyuser
      SPARKY_FITNESS_APP_DB_PASSWORD: sparkypass
      SPARKY_FITNESS_DB_USER: sparkyuser
      SPARKY_FITNESS_DB_PASSWORD: sparkypass
      SPARKY_FITNESS_DB_HOST: sparkyfitness-db
      SPARKY_FITNESS_DB_NAME: sparky
      SPARKY_FITNESS_DB_PORT: 5432
      SPARKY_FITNESS_SERVER_PORT: 3010
      NODE_ENV: production
      TZ: Europe/Berlin
      SPARKY_FITNESS_API_ENCRYPTION_KEY: a3dde95c371ff338c576dad7e295751bccc3b25ab7af6d262a5a0a4a9ae893a5
      JWT_SECRET: k35iTUx8kxWeRFRueIAiGl3I6KMkW11d2tozhffvr+A=
      SPARKY_FITNESS_FRONTEND_URL: http://umbrel-2.local:8944 #http://${DEVICE_DOMAIN_NAME}:8944
      SPARKY_FITNESS_DISABLE_SIGNUP: "false"
      SPARKY_FITNESS_FORCE_EMAIL_LOGIN: "true"
    volumes:
      - ${APP_DATA_DIR}/uploads:/app/SparkyFitnessServer/uploads
      - ${APP_DATA_DIR}/backup:/app/SparkyFitnessServer/backup

  sparkyfitness-web:
    image: codewithcj/sparkyfitness:latest
    depends_on:
      - sparkyfitness-server
    environment:
      SPARKY_FITNESS_SERVER_HOST: sparkyfitness-server
      SPARKY_FITNESS_SERVER_PORT: 3010
