version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-homehub_web_1
      APP_PORT: 5000

  web:
    image: ghcr.io/surajverma/homehub:latest
    restart: on-failure
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=umbrel
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/app/uploads
      - ${APP_DATA_DIR}/data/media:/app/media
      - ${APP_DATA_DIR}/data/pdfs:/app/pdfs
      - ${APP_DATA_DIR}/data/app_data:/app/data
      - ${APP_DATA_DIR}/data/config/config.yml:/app/config.yml:ro
