version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-writefreely_app_1
      APP_PORT: 8080

  db:
    image: mariadb:11.4-noble
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_SEED}
      MYSQL_DATABASE: writefreely
      MYSQL_USER: writefreelyuser
      MYSQL_PASSWORD: writefreelypass
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql

  app:
    image: writeas/writefreely:latest
    user: 0:0
    working_dir: /go
    depends_on:
      - db
    environment:
      WRITEFREELY_ADMIN_USER: admin
      WRITEFREELY_ADMIN_PASSWORD: umbrel
    volumes:
      - ${APP_DATA_DIR}/data:/go
    command: >
      sh -c "
        /go/cmd/writefreely/writefreely -c /go/config.ini --gen-keys || true;
        /go/cmd/writefreely/writefreely -c /go/config.ini --init-db || true;
        /go/cmd/writefreely/writefreely -c /go/config.ini --create-admin ${WRITEFREELY_ADMIN_USER}:${WRITEFREELY_ADMIN_PASSWORD} || true;
        /go/cmd/writefreely/writefreely -c /go/config.ini
      "
