version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-writefreely_web_1
      APP_PORT: 8080

  web:
    image: writeas/writefreely:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    depends_on:
      - db

  db:
    image: lscr.io/linuxserver/mariadb
    restart: on-failure
    volumes: 
      - ${APP_DATA_DIR}/data/db:/config
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Etc/UTC
      - MYSQL_DATABASE=writefreely
      - MYSQL_USER=writefreely
      - MYSQL_PASSWORD=P@ssw0rd
