version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-writefreely_web_1
      APP_PORT: 8080

  web:
    image: writeas/writefreely:latest
    volumes:
      - ${APP_DATA_DIR}/data/web-keys:/go/keys
      - ${APP_DATA_DIR}/data/config/config.ini:/go/config.ini
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: writefreely
      MYSQL_ROOT_PASSWORD: dbpassword
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
