version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-writefreely_app_1
      APP_PORT: 8080

  db:
    image: mariadb:11.4-noble
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: writefreely
      MYSQL_USER: writefreelyuser
      MYSQL_PASSWORD: writefreelypass
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql

  app:
    image: algernon/writefreely:latest
    user: 0:0
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/data/config/config.ini:/go/config.ini
    #command: ["writefreely", "-c", "/data/config/config.ini"]
    depends_on:
      - db
