version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-writefreely_app_1
      APP_PORT: 8080

  app:
    image: writeas/writefreely:latest
    volumes:
      - ${APP_DATA_DIR}/config/config.ini:/go/config.ini
      - ${APP_DATA_DIR}/keys:/go/keys
      - ${APP_DATA_DIR}/pages:/go/pages
      - ${APP_DATA_DIR}/static:/go/static
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=writefreely
      - DATABASE_USER=writefreely
      - DATABASE_PASSWORD=${APP_SEED}
    depends_on:
      - db

  db:
    image: lscr.io/linuxserver/mariadb
    volumes:
      - ${APP_DATA_DIR}/db:/config
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Etc/UTC
      - MYSQL_DATABASE=writefreely
      - MYSQL_USER=writefreely
      - MYSQL_PASSWORD=${APP_SEED}
      - MYSQL_ROOT_PASSWORD=${APP_SEED}
