version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-writefreely_app_1
      APP_PORT: 8080

  db:
    image: mariadb:11.4.9-noble
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: writefreely
      MYSQL_USER: writefreelyuser
      MYSQL_PASSWORD: writefreelypass
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql

  app:
    image: writeas/writefreely:latest
    user: "0:0"
    depends_on:
      - db
    volumes:
      - ${APP_DATA_DIR}/config/config.ini:/go/config.ini
      - ${APP_DATA_DIR}/keys:/go/keys
    command: >
      sh -c "/go/cmd/writefreely/writefreely -c /go/config.ini --init-db || true;
             /go/cmd/writefreely/writefreely -c /go/config.ini --create-admin admin:umbrel || true;
             /go/cmd/writefreely/writefreely -c /go/config.ini"
