version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ashigaru_app_1
      APP_PORT: 7682

  app:
    image: dennysubke/ashigaru-terminal:1.0.0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/tor:/home/ashigaru/.ashigaru/tor
      - ${APP_DATA_DIR}/data/wallets:/home/ashigaru/.ashigaru/wallets
      - ${APP_DATA_DIR}/data/config:/home/ashigaru/.ashigaru
