version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ashigaru_app_1
      APP_PORT: 7682

  app:
    image: dennysubke/ashigaru-terminal:1.0.0@sha256:b4b8ab092ab5231bbd50390d0a72e536bede6f5c5b6fae443f8af857f75cfb68
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/home/ashigaru
