version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ashigaru_terminal_1
      APP_PORT: 7682

  terminal:
    image: dennysubke/ashigaru-terminal:1.0.0@sha256:28b6f23a5bcaa72ebaf063be10cf96b00cbc9fb80c92079c8327a90e3f218c0b
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/tor:/home/ashigaru/.ashigaru/tor
      - ${APP_DATA_DIR}/data/wallets:/home/ashigaru/.ashigaru/wallets
      - ${APP_DATA_DIR}/data/config:/home/ashigaru/.ashigaru
