version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ashigaru_app_1
      APP_PORT: 7682

  app:
    image: dennysubke/ashigaru-terminal:1.0.0@sha256:f5cc32934dec55097b96fdbf2c4dcb402c02756eafd788a5e942b3a4d06e9863
    volumes:
      - ${APP_DATA_DIR}/data:/home/ashigaru
