version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-postgresus_web_1
      APP_PORT: 4005

  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgresus_db
    volumes:
      - ${APP_DATA_DIR}/postgres-data:/var/lib/postgresql

  web:
    image: rostislavdugin/postgresus:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/postgresus-data
