version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: smw_web_1
      APP_PORT: 80

  web:
    image: dennysubke/supermariowar-web:1.0.0@sha256:c3c1eedc8507626101d54e828f17d40a34b6432e2a92495a9c79317a346b58a9
    volumes:
      - ${APP_DATA_DIR}/data:/data