version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-smw_web_1
      APP_PORT: 80

  web:
    image: dennysubke/supermariowar-web:1.0.1@sha256:3771b23119caefe664f8d80365cbe8b802a68367b17441152679a3fcc025f761
    volumes:
      - ${APP_DATA_DIR}/data:/data
