version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-smw_web_1
      APP_PORT: 80

  web:
    image: dennysubke/supermariowar-web:1.0.0@sha256:68542863d068ce2894cda4df2d636090a93951d6d0f0cdca9c4758df05036864
    volumes:
      - ${APP_DATA_DIR}/data:/data
