version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-smw_web_1
      APP_PORT: 80

  web:
    image: dennysubke/supermariowar-web:1.0.1@sha256:74166cd0ee74169cb8c7415c458de4a27ba12ab3ab608291e069e89a4ba429de
    volumes:
      - ${APP_DATA_DIR}/data:/data
