version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-smw_web_1
      APP_PORT: 80

  web:
    image: dennysubke/supermariowar-web:1.0.0@sha256:77cd425847584e830e5db1591f3abaeb16b06e64eb4d24ed8310db9a87758f00
    volumes:
      - ${APP_DATA_DIR}/data:/data
