version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-youtarr_app_1
      APP_PORT: 3011

  db:
    image: mariadb:10.3
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 123qweasd
      MYSQL_DATABASE: youtarr
      MYSQL_USER: root
      MYSQL_PASSWORD: 123qweasd
    volumes:
      - ${APP_DATA_DIR}/database:/var/lib/mysql
      - ${APP_DATA_DIR}/config/mariadb.cnf:/etc/mysql/conf.d/charset.cnf:ro

  app:
    image: dialmaster/youtarr:latest
    restart: on-failure
    user: "0:0"
    depends_on:
      - db
    environment:
      IN_DOCKER_CONTAINER: 1
      TZ: UTC
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123qweasd
      DB_NAME: youtarr
      LOG_LEVEL: warn
      YOUTUBE_OUTPUT_DIR: ${APP_DATA_DIR}/videos
    volumes:
      - ${APP_DATA_DIR}/videos:/usr/src/app/data
      - ${APP_DATA_DIR}/server_images:/app/server/images
      - ${APP_DATA_DIR}/config:/app/config
      - ${APP_DATA_DIR}/jobs:/app/jobs
