version: "3.7"

services:
  web:
    image: localstack/localstack:latest
    environment:
      DEBUG: "0"
      USE_SSL: "0"
      LOCALSTACK_VOLUME_DIR: /var/lib/localstack
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
