version: "3.7"

app_proxy:
  environment:
    APP_HOST: denny-localstack_web_1
    APP_PORT: 4566

services:
  web:
    image: localstack/localstack:latest
    environment:
      DEBUG: "0"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
