version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-homepage_app_1
      APP_PORT: 3000

  app:
    image: gethomepage/homepage:latest
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config:rw
      - ${APP_DATA_DIR}/data/public:/app/public/images:rw
      - /var/run/docker.sock:/var/run/docker.sock
