version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-rocketchat_app_1
      APP_PORT: 3000

  db:
    image: mongo:7.0.25@sha256:a814f930db8c4514f5fe5dc3e489f58637fb7ee32a7b9bb0b7064d3274e90b8e
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - ${APP_DATA_DIR}/data/db:/data/db
    restart: on-failure

  init-replica:
    image: mongo:7
    depends_on:
      - db
    entrypoint:
      - bash
      - -lc
      - >
        mongosh --host db:27017 --quiet --eval
        'try{if(rs.status().ok!=1)rs.initiate({_id:"rs0",members:[{_id:0,host:"db:27017"}]});1}catch(e){rs.initiate({_id:"rs0",members:[{_id:0,host:"db:27017"}]})};'
    restart: "no"

  app:
    image: rocketchat/rocket.chat:7.12.0@sha256:658180bd79c0dca402f50c04371bbadf27fe2dffd5bf4a763590a5734416ffe4
    environment:
      MONGO_URL: mongodb://db:27017/rocketchat?replicaSet=rs0&retryWrites=false
      MONGO_OPLOG_URL: mongodb://db:27017/local?replicaSet=rs0
      ROOT_URL: http://${APP_DOMAIN}:3111
      URL: http://${APP_DOMAIN}:3111
      PORT: "3000"
      DEPLOY_METHOD: docker
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/app/uploads
    restart: on-failure
    depends_on:
      - db
      - init-replica
