version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-rocketchat_rocketchat_1
      APP_PORT: 3000

  db:
    image: mongo:7
    hostname: rocketchat-db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - ${APP_DATA_DIR}/data/db:/data/db
    restart: on-failure:5

  init-replica:
    image: mongo:7
    depends_on:
      - db
    entrypoint:
      - bash
      - -lc
      - >
        mongosh --host rocketchat-db:27017 --quiet --eval
        'try{if(rs.status().ok!=1)rs.initiate({_id:"rs0",members:[{_id:0,host:"rocketchat-db:27017"}]});1}catch(e){rs.initiate({_id:"rs0",members:[{_id:0,host:"rocketchat-db:27017"}]})};'
    restart: "no"

  rocketchat:
    image: rocketchat/rocket.chat:latest
    hostname: rocketchat
    environment:
      MONGO_URL: mongodb://rocketchat-db:27017/rocketchat?replicaSet=rs0&retryWrites=false
      MONGO_OPLOG_URL: mongodb://rocketchat-db:27017/local?replicaSet=rs0
      ROOT_URL: http://${APP_DOMAIN}:3111
      URL: http://${APP_DOMAIN}:3111
      PORT: "3000"
      DEPLOY_METHOD: docker
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/app/uploads
    restart: on-failure:5
    depends_on:
      - db
      - init-replica
