version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-mullvad-browser_web_1
      APP_PORT: 5880
      PROXY_AUTH_ADD: "false"
  web:
    image: dennysubke/mullvadbrowser:15.0.1@sha256:b68c69d60c70c0a1a9dc3be3cf94270ff3b11fd716ddb0176ac22bbe1f7de49c
    restart: on-failure
    environment:
      - TZ=Europe/Berlin
      - DARK_MODE=1
      - WEB_AUDIO=1
    volumes:
      - ${APP_DATA_DIR}/config:/config
