version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-withoutbg_withoutbg_1
      APP_PORT: 80

  withoutbg:
    image: withoutbg/app:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
