version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-medama_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/medama-io/medama:v0.6.1@sha256:7b0ea9cab4fc3ca3ebf73fdb73822e275a6f2cfbeb9c272c3b6be6512755cf4a
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
