version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-ontime_ontime_1
      APP_PORT: 4001

  ontime:
    image: getontime/ontime:v4.1.0@sha256:91a7d2d4e22ef778234dea0cd8e5790bf29de3d5fee25e269676203644beb946
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      TZ: Europe/Berlin
    ports:
      - "4088:8888/udp"
      - "4099:9999/udp"
