version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-manyfold_app_1
      APP_PORT: 3214

  app:
    image: ghcr.io/manyfold3d/manyfold:latest
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: postgres-server
      DATABASE_PORT: 5432
      DATABASE_NAME: manyfold
      DATABASE_USER: manyfold
      DATABASE_PASSWORD: password

      SECRET_KEY_BASE: a_nice_long_random_string

      REDIS_URL: redis://redis-server:6379/1

      PUID: 1000
      PGID: 1000
    depends_on:
      - postgres-server
      - redis-server
    volumes:
      - ${APP_DATA_DIR}/data/models:/models
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID

  postgres-server:
    image: postgres:15
    environment:
      POSTGRES_USER: manyfold
      POSTGRES_PASSWORD: password
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data

  redis-server:
    image: redis:7
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
